#! /bin/bash
if [[ $# -lt 2 ]]; then
	echo "Not enough parameters"
	exit -1
fi
if [[ !(-d "$1") ]]; then
	echo "Directory does not exist"
	exit -1
fi
input_letter="`echo "$2" | tr '[:upper:]' '[:lower:]'`"
counter=0
for file in "$1"/*; do
	if [[ -f "$file" ]]; then
		file_1st_letter="`head -1 "$file" | cut -c1 | tr '[:upper:]' '[:lower:]'`"
		if [[ "$file_1st_letter" == "$input_letter" ]]; then
		(( counter++ ))
		fi
	elif [[ -d "$file" ]]; then
		(( counter = counter+`"$0" "$file" "$input_letter"` ))
	fi 
done
echo "$counter"
